### ISSUE TITLE
Error opening DVBC.xml

### ISSUE THREAD

**Issue by mtzro2003** [onka13/Onka-Philips-Channel-Editor#1]
Hi!

I'm trying to edit the channel list form a Philips 32PFT4132/12 and, when opening DVBC.xml, it gives the following error:

> System.InvalidOperationException: There is an error in XML document (5, 60). ---> System.OverflowException: Value was either too large or too small for a UInt16.

Do you have any clue about what wrong?
The DVBC.xml file is, of course, exported directly form the TV.
Here is the zipped file. 
[DVBC.zip](https://github.com/onka13/Onka-Philips-Channel-Editor/files/1691651/DVBC.zip)

Thanks!

**Comment by onka13** [comment]
Hi @mtzro2003, Thanks for feedback. I've just fix the issue. Could you please inform me if everything is ok?
Thanks

**Comment by mtzro2003** [comment]
It's working, I successfully opened the file.
Many thanks! :hugs: 
Now working on arranging the channels 😄 

Improvements suggestion:
 - sort channels alphabetically
 - select and move several channels at once
 - copy channel - for example make a duplicate of a channel on a different channel number.

**Comment by onka13** [comment]
Glad that it is solved. Thanks for suggestion, I'll think about that.
